### ISSUE TITLE
icon pack build doesn't work with fontawesome icons

### ISSUE THREAD

**Issue by mathiz11** [tinymce/oxide-icon-pack-template#1]
I downloaded fontawesome icons (5.12.1). I copied a part of svg files. When I build the icon pack, no icons have been displayed in icons.html but they are in body.

Thanks

Mathis

**Comment by tinydylan** [comment]
Hi @mathiz11,

Are you able to please create a simple self-contained example of the issue? e.g. as a zip file or a codepen.io example?

Thanks,

Dylan Just
Tiny
